/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.NavigationController;
import controllers.OrderController;

/**
 *
 * @author eric
 */
public class ManageOrder extends javax.swing.JFrame {

    private OrderController controller;
    private NavigationController navigation;
    
    /**
     * Creates new form Orders
     */
    public ManageOrder( OrderController oc, NavigationController nc ) {
        
        this.controller = oc;
        this.navigation = nc;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        orderDetailsScrollPane = new javax.swing.JScrollPane();
        orderItemsTable = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        orderDetailLabel = new javax.swing.JLabel();
        menuItemsLabel = new javax.swing.JLabel();
        orderStatusPane = new javax.swing.JPanel();
        taxLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        tipLabel = new javax.swing.JLabel();
        tipAmountField = new javax.swing.JTextField();
        subtotalAmountLabel = new javax.swing.JLabel();
        taxAmountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        menuSelectionPane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order");

        orderItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderDetailsScrollPane.setViewportView(orderItemsTable);

        removeButton.setText("Remove");

        backButton.setText("Back");

        orderDetailLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        orderDetailLabel.setText("Order Detail");

        menuItemsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        menuItemsLabel.setText("Select Menu Items");

        taxLabel.setText("Tax:");

        subtotalLabel.setText("Subtotal:");

        tipLabel.setText("Tip:");

        tipAmountField.setText("$tip amount");

        subtotalAmountLabel.setText("$subtotal amount");

        taxAmountLabel.setText("$tax amount");

        commentsTextArea.setColumns(20);
        commentsTextArea.setRows(5);
        jScrollPane1.setViewportView(commentsTextArea);

        jLabel1.setText("Comments:");

        org.jdesktop.layout.GroupLayout orderStatusPaneLayout = new org.jdesktop.layout.GroupLayout(orderStatusPane);
        orderStatusPane.setLayout(orderStatusPaneLayout);
        orderStatusPaneLayout.setHorizontalGroup(
            orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderStatusPaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
            .add(orderStatusPaneLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(orderStatusPaneLayout.createSequentialGroup()
                        .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(subtotalLabel)
                            .add(taxLabel)
                            .add(tipLabel))
                        .add(24, 24, 24)
                        .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tipAmountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(taxAmountLabel)
                            .add(subtotalAmountLabel))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderStatusPaneLayout.setVerticalGroup(
            orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderStatusPaneLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(subtotalLabel)
                    .add(subtotalAmountLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(taxLabel)
                    .add(taxAmountLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(orderStatusPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tipLabel)
                    .add(tipAmountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        submitButton.setText("Submit Order");

        org.jdesktop.layout.GroupLayout menuSelectionPaneLayout = new org.jdesktop.layout.GroupLayout(menuSelectionPane);
        menuSelectionPane.setLayout(menuSelectionPaneLayout);
        menuSelectionPaneLayout.setHorizontalGroup(
            menuSelectionPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 375, Short.MAX_VALUE)
        );
        menuSelectionPaneLayout.setVerticalGroup(
            menuSelectionPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 486, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(backButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(removeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(orderDetailsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .add(0, 0, Short.MAX_VALUE)
                                        .add(orderStatusPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(18, 18, 18)
                                .add(menuSelectionPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(113, 113, 113)
                                .add(orderDetailLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(menuItemsLabel)
                                .add(114, 114, 114))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(submitButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(backButton)
                        .add(orderDetailLabel))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, menuItemsLabel))
                .add(2, 2, 2)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(removeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createSequentialGroup()
                            .add(orderDetailsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(orderStatusPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(menuSelectionPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(submitButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextArea commentsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel menuItemsLabel;
    private javax.swing.JPanel menuSelectionPane;
    private javax.swing.JLabel orderDetailLabel;
    private javax.swing.JScrollPane orderDetailsScrollPane;
    private javax.swing.JTable orderItemsTable;
    private javax.swing.JPanel orderStatusPane;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel subtotalAmountLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel taxAmountLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField tipAmountField;
    private javax.swing.JLabel tipLabel;
    // End of variables declaration//GEN-END:variables
}
