/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.MenuController;
import controllers.NavigationController;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

/**
 * This JFrame provides a GUI for the user to modify the menu of the restaurant.
 * @author ejames788
 */
public class Menu extends javax.swing.JFrame {

    //PUBLIC CONSTANS
    public static final int PRICE_COL = 0;
    public static final int NAME_COL = 1;
    public static final int DESCRIPTION_COL = 2;
    public static final String NAME_COLUMN_NAME = "Name";
    public static final String PRICE_COLUMN_NAME = "Price";
    public static final String DESCRIPTION_COLUMN_NAME = "Description";
    //PRIVATE CONTROLLERS
    private MenuController controller;
    private NavigationController navigation;
    
    /**
     * Creates a new Menu frame with a navigation controller and a controller to
     * handle business logic subsequent to user-fired control events.
     * @param menuController an instance of {@link MenuController}
     * @param navigationController an instance of {@link NavigationController}
     */
    public Menu( MenuController mc, NavigationController nc ) {
        
        this.controller = mc;
        this.navigation = nc;
                
        initComponents();
        this.configureTable();
        
        if ( this.menuItemTable.getRowCount() > 0 ) {
            ListSelectionModel selectionModel = this.menuItemTable.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
            this.menuItemTable.setSelectionModel(selectionModel);
        }
        
    }
    
    /**
     * Configures the table's name, model, and column names.
     */
    private void configureTable() {
        this.menuItemTable.setName("MenuItemTable");
        this.menuItemTable.setModel( this.controller.getTableModel() );
        
        //name the tables columns
        TableColumnModel cm = this.menuItemTable.getColumnModel();
        for (int colIndex = PRICE_COL; colIndex <= DESCRIPTION_COL; colIndex++) {
            switch(colIndex) {
                case PRICE_COL:
                    cm.getColumn(PRICE_COL).setHeaderValue(PRICE_COLUMN_NAME);
                    break;
                case NAME_COL:
                    cm.getColumn(NAME_COL).setHeaderValue(NAME_COLUMN_NAME);
                    break;
                case DESCRIPTION_COL:
                    cm.getColumn(DESCRIPTION_COL).setHeaderValue(DESCRIPTION_COLUMN_NAME);
                    break;
                default:
                    break;
                    
            }
        
        }
    }
         
    /**
     * Returns 
     * @return 
     *
    public JTable getTable() {
        return this.menuItemTable;
    }*/
    
    /**
     * Hides the administrator functionality from a basic user.
     */
    public void hideAdminFunctions() {
        this.createMenuItemButton.setVisible(false);
        this.deleteMenuItemButton.setVisible(false);
        this.updateItemButton.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuScrollPane = new javax.swing.JScrollPane();
        menuItemTable = new javax.swing.JTable();
        TitlePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        createMenuItemButton = new javax.swing.JButton();
        updateItemButton = new javax.swing.JButton();
        deleteMenuItemButton = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        menuScrollPane.setViewportView(menuItemTable);

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel1.setText("Menu");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout TitlePaneLayout = new org.jdesktop.layout.GroupLayout(TitlePane);
        TitlePane.setLayout(TitlePaneLayout);
        TitlePaneLayout.setHorizontalGroup(
            TitlePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TitlePaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(backButton)
                .add(119, 119, 119)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitlePaneLayout.setVerticalGroup(
            TitlePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, TitlePaneLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(TitlePaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(backButton))
                .add(11, 11, 11))
        );

        createMenuItemButton.setText("New Menu Item");
        createMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenuItemButtonActionPerformed(evt);
            }
        });

        updateItemButton.setText("Update Selected");
        updateItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemButtonActionPerformed(evt);
            }
        });

        deleteMenuItemButton.setText("Delete Selected");
        deleteMenuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(deleteMenuItemButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(updateItemButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(createMenuItemButton)
                .add(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(createMenuItemButton)
                    .add(updateItemButton)
                    .add(deleteMenuItemButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TitlePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, menuScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(TitlePane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(menuScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 387, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.navigation.back();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenuItemButtonActionPerformed
        // TODO add your handling code here:
        this.controller.showMenuItemDialog(this);
    }//GEN-LAST:event_createMenuItemButtonActionPerformed

    private void updateItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemButtonActionPerformed
        // TODO add your handling code here:
        this.controller.showMenuItemDialog(this, this.menuItemTable.getSelectedRow());
    }//GEN-LAST:event_updateItemButtonActionPerformed

    private void deleteMenuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemButtonActionPerformed
        // TODO add your handling code here:
        this.controller.showDeleteMenuItemPrompt(this, this.menuItemTable.getSelectedRow());
    }//GEN-LAST:event_deleteMenuItemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TitlePane;
    private javax.swing.JButton backButton;
    private javax.swing.JButton createMenuItemButton;
    private javax.swing.JButton deleteMenuItemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable menuItemTable;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JButton updateItemButton;
    // End of variables declaration//GEN-END:variables

}
