/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.MenuController;
import entities.MenuItem;
import javax.swing.JOptionPane;

/**
 * This JDialog provides a GUI for the user to add or modify menu items.
 * @author eric
 */
public class MenuItemDialog extends javax.swing.JDialog {

    private MenuController controller;
    private boolean isUpdating;
    
    /**
     * Creates a new MenuItemDialog.
     * @param parent is a {@link JFrame} representing the owner of this {@link JDialog}.
     * @param menuController is the menu controller.
     * @param modal is a boolean specifying whether or not the user may freely change the position of the dialog.
     * @param isUpdating is a boolean specifying whether or not this menu item dialog will be creating or updating an item.
     */
    public MenuItemDialog(java.awt.Frame parent, MenuController mc, boolean modal, boolean isUpdating ) {
        super(parent, modal);
        
        this.controller = mc;
        
        initComponents();
        
        this.isUpdating = isUpdating;
        if (this.isUpdating) {
            this.commitItemChangesButton.setText("Update Menu Item");
        }

    }

    /**
     * Populates the text fields with the model's corresponding properties to update.
     * @param item 
     */
    public void populateFields( MenuItem item ) {

        this.nameField.setText(item.getName() );
        this.priceField.setText( item.getPrice().toString() );
        this.descriptionTextArea.setText(item.getDescription() );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commitItemChangesButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Item Dialog");

        commitItemChangesButton.setText("Add Item");
        commitItemChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitItemChangesButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");

        priceLabel.setText("Price:");

        descriptionLabel.setText("Description:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel1.setText("Enter Menu Item");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(nameLabel)
                            .add(priceLabel)
                            .add(descriptionLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(nameField)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, priceField)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelButton)
                        .add(18, 18, 18)
                        .add(commitItemChangesButton)))
                .add(41, 41, 41))
            .add(layout.createSequentialGroup()
                .add(167, 167, 167)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(priceField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(priceLabel))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(descriptionLabel)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(commitItemChangesButton)
                            .add(cancelButton))
                        .add(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void commitItemChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitItemChangesButtonActionPerformed
        // TODO add your handling code here:
        //double value;
      /*try{
            this.nameField.getText();    
            this.priceField.getText();
            this.descriptionTextArea.getText();
                throw new Exception("Enter Members");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,
                "Need to put in all the information.", "Menu Item Error", JOptionPane.ERROR_MESSAGE);
        }*/
        if((this.nameField.getText().length() == 0) || (this.priceField.getText().length() == 0) 
                || (this.descriptionTextArea.getText().length() == 0)){
            
                this.noInfo();
            
        }
        else{
        try {
        // String textValue = the string from your JTextField
            Double.parseDouble(this.priceField.getText());

        }
        catch(NumberFormatException e) {
        // if the code gets to here, it was NOT recognizable as a double
          JOptionPane.showMessageDialog(this,
                "Enter a numeric value for the price.", "Menu Item Error", 
                JOptionPane.ERROR_MESSAGE);  
        }
       

        if (this.isUpdating) {
            this.controller.updateItem( 
                    this.nameField.getText(), 
                    this.priceField.getText(), 
                    this.descriptionTextArea.getText()
                    );
        }
        else {
            this.controller.createItem( 
                    this.nameField.getText(),
                    this.priceField.getText(),
                    this.descriptionTextArea.getText()
                    );
        }
       }
    }//GEN-LAST:event_commitItemChangesButtonActionPerformed
    /**
      * Displays an error message if the user did not put in all the information for the menu item.
      */   
     private void noInfo() {
        JOptionPane.showMessageDialog(this,
                "You need to put in all the information.", "Menu Item Error", JOptionPane.ERROR_MESSAGE);
    }   
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton commitItemChangesButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
