/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.NavigationController;
import controllers.ReservationController;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author eric
 */
public class Reservations extends javax.swing.JFrame {

    //PRIVATE CONTROLLERS
    private ReservationController controller;
    private NavigationController navigation;
    
    //PUBLIC CONSTANTS
    public static final int GROUP_COL = 0;
    public static final int NUMBER_COL = 1;
    public static final int DATE_COL = 2;
    public static final int TIME_COL = 3;
    public static final String GROUP_COLUMN_NAME = "Group's Name";
    public static final String NUMBER_COLUMN_NAME = "# of People";
    public static final String DATE_COLUMN_NAME = "Date";
    public static final String TIME_COLUMN_NAME = "Time";
    /**
     * Creates new form Reservations
     */
    public Reservations( ReservationController rc, NavigationController nc ) {
        
        this.controller = rc;
        this.navigation = nc;
        
        initComponents();
        
        this.configureTable();
    }
    
        /**
     * Configures the table's name, model, and column names.
     */
    private void configureTable() {
        this.reservationsTable.setName("ReservationsTable");
        this.reservationsTable.setModel( this.controller.getTableModel() );
        
        //name the tables columns
        TableColumnModel cm = this.reservationsTable.getColumnModel();
        for (int colIndex = GROUP_COL; colIndex <= TIME_COL; colIndex++) {
            switch(colIndex) {
                case GROUP_COL:
                    cm.getColumn(GROUP_COL).setHeaderValue(GROUP_COLUMN_NAME);
                    break;
                case NUMBER_COL:
                    cm.getColumn(NUMBER_COL).setHeaderValue(NUMBER_COLUMN_NAME);
                    break;
                case DATE_COL:
                    cm.getColumn(DATE_COL).setHeaderValue(DATE_COLUMN_NAME);
                    break;
                case TIME_COL:
                    cm.getColumn(TIME_COL).setHeaderValue(TIME_COLUMN_NAME);
                    break;
                default:
                    break;
                    
            }
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageReservationsLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        reservationsScrollPane = new javax.swing.JScrollPane();
        reservationsTable = new javax.swing.JTable();
        makeReservationButton = new javax.swing.JButton();
        deleteReservation = new javax.swing.JButton();
        updateReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservations");

        manageReservationsLabel.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        manageReservationsLabel.setText("Manage Reservations");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        reservationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reservationsScrollPane.setViewportView(reservationsTable);

        makeReservationButton.setText("Make Reservation");
        makeReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReservationButtonActionPerformed(evt);
            }
        });

        deleteReservation.setText("Remove Reservation");
        deleteReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteReservationActionPerformed(evt);
            }
        });

        updateReservation.setText("Update Reservation");
        updateReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateReservationActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(backButton)
                        .add(60, 60, 60)
                        .add(manageReservationsLabel)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jSeparator1)
                    .add(reservationsScrollPane))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(updateReservation)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteReservation)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(makeReservationButton)
                .add(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backButton)
                    .add(manageReservationsLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(reservationsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 376, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(makeReservationButton)
                    .add(deleteReservation)
                    .add(updateReservation))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.navigation.back();
    }//GEN-LAST:event_backButtonActionPerformed

    private void makeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReservationButtonActionPerformed
        // TODO add your handling code here:
        this.controller.showReservationDialog(this);
    }//GEN-LAST:event_makeReservationButtonActionPerformed

    private void deleteReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteReservationActionPerformed
        // TODO add your handling code here:
        this.controller.showDeleteReservationPrompt(this, this.reservationsTable.getSelectedRow());
    }//GEN-LAST:event_deleteReservationActionPerformed

    private void updateReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateReservationActionPerformed
        // TODO add your handling code here:
        this.controller.showReservationDialog(this, this.reservationsTable.getSelectedRow());
    }//GEN-LAST:event_updateReservationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteReservation;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton makeReservationButton;
    private javax.swing.JLabel manageReservationsLabel;
    private javax.swing.JScrollPane reservationsScrollPane;
    private javax.swing.JTable reservationsTable;
    private javax.swing.JButton updateReservation;
    // End of variables declaration//GEN-END:variables
}
