/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.ReservationController;
import entities.Reservation;
import javax.swing.JOptionPane;
/**
 *
 * @author Nishad Shah
 */
public class ReservationDialog extends javax.swing.JDialog {
    private ReservationController controller;
    private boolean isUpdating;
    /**
     * Creates new form ReservationDialog
     * @param parent is a {@link JFrame} representing the owner of this {@link JDialog}.
     * @param reservationController is the reservation controller.
     * @param modal is a boolean specifying whether or not the user may freely change the position of the dialog.
     * @param isUpdating is a boolean specifying whether or not this reservation dialog will be creating or updating a reservation.
     */
    public ReservationDialog(java.awt.Frame parent, ReservationController rc, boolean modal, boolean isUpdating) {
        super(parent, modal);
        
        this.controller = rc;
        
        initComponents();
        
        this.isUpdating = isUpdating;
        if (this.isUpdating) {
            this.commitItemChangesButton.setText("Update Reservation");
        }
    }
        /**
     * Populates the text fields with the model's corresponding properties to update.
     * @param item 
     */
    public void populateFields( Reservation item ) {

        this.groupText.setText(item.getGroupName() );
        this.nopText.setText( item.getNumberOfPeople());
        this.dateText.setText(item.getDate());
        this.timeText.setText(item.getTime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupLabel = new javax.swing.JLabel();
        numOfPeople = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        groupText = new javax.swing.JTextField();
        nopText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        commitItemChangesButton = new javax.swing.JButton();
        timeText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservation Dialog");

        groupLabel.setText("Group's Name:");

        numOfPeople.setText("Number of people:");

        dateLabel.setText("Date:");

        timeLabel.setText("Time:");

        groupText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupTextActionPerformed(evt);
            }
        });

        dateText.setToolTipText("");

        commitItemChangesButton.setText("Submit");
        commitItemChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitItemChangesButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        jLabel1.setText("Enter Reservation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(commitItemChangesButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(groupLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(groupText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(timeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timeText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numOfPeople)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nopText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel)
                    .addComponent(groupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfPeople)
                    .addComponent(nopText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commitItemChangesButton)
                    .addComponent(cancelButton))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupTextActionPerformed

    private void commitItemChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitItemChangesButtonActionPerformed
        // TODO add your handling code here:
       
       if((this.groupText.getText().length() == 0) || (this.nopText.getText().length() == 0) 
               || (this.dateText.getText().length() == 0) || (this.timeText.getText().length() == 0))
       {
           this.noInfo();
           
                
       }
    
       else{
        if (this.isUpdating) {
            this.controller.updateReservation( 
                    this.groupText.getText(), 
                    this.nopText.getText(), 
                    this.dateText.getText(),
                    this.timeText.getText()
                    );
        }
        else {
            this.controller.createReservation( 
                    this.groupText.getText(), 
                    this.nopText.getText(), 
                    this.dateText.getText(),
                    this.timeText.getText()
                    );
        }
      }
    }//GEN-LAST:event_commitItemChangesButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
      * Displays an error message if the user did not put in all the information for the reservation.
      */ 
    private void noInfo() {
        JOptionPane.showMessageDialog(this,
                "You need to put in all the information.", "Reservation Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton commitItemChangesButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JTextField groupText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nopText;
    private javax.swing.JLabel numOfPeople;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeText;
    // End of variables declaration//GEN-END:variables
}
